resolver: lts-7.0
packages:
- '.'
- location:
   git: git@github.com:bitonic/haskell-opencv.git
   commit: c7d181a4c16ccdda6e967851f75f5afcfd52d48b
  extra-dep: true
extra-deps:
- fltkhs-0.4.0.9
flags: {}
extra-package-dbs: []
