resolver: lts-7.15
packages:
- '.'
- location:
   git: git@github.com:LumiGuide/haskell-opencv.git
   commit: 4594ef0d63b990cd57f15068de3e97ce9ab8da4a
  extra-dep: true
extra-deps:
- fltkhs-0.5.0.1
flags: {}
extra-package-dbs: []
