resolver: lts-9.10
packages:
- '.'
- location:
   git: git@github.com:LumiGuide/haskell-opencv.git
   commit: 916001562c6295d229c9dd846f859af5e00e6a1e
  extra-dep: true
  subdirs:
  - opencv
  - opencv-extra

extra-deps:
- fltkhs-0.5.4.1
- repa-3.4.1.3
flags: {}
extra-package-dbs: []
