resolver: lts-7.0
packages:
- '.'
- location:
   git: git@github.com:LumiGuide/haskell-opencv.git
   commit: 0dd31b9058f06518a945382f0128ade831541427
  extra-dep: true
extra-deps:
- fltkhs-0.4.0.9
flags: {}
extra-package-dbs: []
